[package]
name = "pg-queue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = { version = "0.19.7", features = ["with-uuid-1", "with-time-0_3"] }
uuid = "1.4.1"
