version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
